"""Corsi di studio della Federico II, raggruppati per Scuola.

Fonte: portale Orientamento Federico II (orientamento.unina.it/corsidistudio), letto il 7 ottobre 2026.
Esclusi i doppioni in inglese di corsi già presenti e i corsi chiusi prima del 2022/23.
Tipo: L = triennale, LM = magistrale, CU = magistrale a ciclo unico.
Per aggiungere un corso basta aggiungere una riga qui.
"""

TYPE_LABELS = {"L": "Triennale", "LM": "Magistrale", "CU": "Ciclo unico"}

COURSES = {
    "Politecnica e delle Scienze di Base": [
        # Architettura
        ("Architettura (ARCH5UE)", "CU"),
        ("Architettura per comunità, territori e ambiente", "LM"),
        ("Architecture & Heritage (ARCHER)", "LM"),
        ("Design for the Built Environment", "LM"),
        ("Design per la Comunità (CO.DE)", "L"),
        ("Pianificazione Territoriale, Urbanistica e Paesaggistico-Ambientale", "LM"),
        ("Scienze dell'Architettura", "L"),
        ("Urbanistica Sostenibile (UrbS)", "L"),
        # Biologia
        ("Biologia", "L"),
        ("Biologia", "LM"),
        ("Biology for One Health", "L"),
        ("Biology of Extreme Environments", "LM"),
        ("Biology and Ecology of the Marine Environment", "LM"),
        ("Marine Biology and Aquaculture", "LM"),
        ("Scienze Biologiche", "LM"),
        ("Scienze Naturali", "LM"),
        ("Scienze per la Natura e per l'Ambiente", "L"),
        # Chimica
        ("Biotecnologie Molecolari e Industriali", "L"),
        ("Biotecnologie Molecolari e Industriali", "LM"),
        ("Chimica", "L"),
        ("Chimica Industriale", "L"),
        ("Industrial Chemistry for Circular and Bio Economy", "LM"),
        ("Scienze Chimiche", "LM"),
        ("Scienze e Tecnologie della Chimica Industriale", "LM"),
        # Fisica, Matematica, Terra
        ("Fisica", "L"),
        ("Fisica", "LM"),
        ("Quantum Science and Engineering", "LM"),
        ("Matematica", "L"),
        ("Matematica", "LM"),
        ("Mathematical Engineering", "LM"),
        ("Geoscienze per l'Ambiente, le Risorse e i Rischi Naturali", "LM"),
        ("Scienze Geologiche", "L"),
        ("Volcanology", "LM"),
        # Ingegneria civile, edile, ambientale
        ("Civil and Environmental Engineering", "L"),
        ("GeCo - Ingegneria Gestionale delle Costruzioni", "L"),
        ("Ingegneria Civile", "L"),
        ("Ingegneria Civile per l'Idraulica e i Trasporti", "LM"),
        ("Ingegneria Edile - Architettura", "CU"),
        ("Ingegneria Edile per la Sostenibilità", "L"),
        ("Ingegneria Edile per la Sostenibilità", "LM"),
        ("Ingegneria per l'Ambiente e il Territorio", "L"),
        ("Ingegneria per l'Ambiente e il Territorio", "LM"),
        ("Ingegneria Strutturale e Geotecnica (STReGA)", "LM"),
        ("Tecnologie Digitali per le Costruzioni (professionalizzante)", "L"),
        ("Transportation Engineering and Mobility", "LM"),
        # Ingegneria elettrica e dell'informazione
        ("Data Science", "LM"),
        ("Electrical Engineering and Information Technology", "L"),
        ("Informatica", "L"),
        ("Informatica", "LM"),
        ("Ingegneria Biomedica", "L"),
        ("Ingegneria Biomedica", "LM"),
        ("Ingegneria dell'Automazione", "L"),
        ("Ingegneria dell'Automazione e Robotica", "LM"),
        ("Ingegneria delle Telecomunicazioni e dei Media Digitali", "L"),
        ("Ingegneria delle Telecomunicazioni e dei Media Digitali", "LM"),
        ("Ingegneria Elettrica", "L"),
        ("Ingegneria Elettrica", "LM"),
        ("Ingegneria Elettronica", "L"),
        ("Ingegneria Elettronica", "LM"),
        ("Ingegneria Informatica", "L"),
        ("Ingegneria Informatica", "LM"),
        ("Meccatronica (professionalizzante)", "L"),
        # Ingegneria industriale, chimica, materiali
        ("Autonomous Vehicle Engineering", "LM"),
        ("Gestione dei Sistemi Aerospaziali per la Difesa (cadetti Accademia Aeronautica)", "L"),
        ("Gestione dei Sistemi Aerospaziali per la Difesa (cadetti Accademia Aeronautica)", "LM"),
        ("Industrial Bioengineering", "LM"),
        ("Ingegneria Aerospaziale", "L"),
        ("Ingegneria Aerospaziale", "LM"),
        ("Ingegneria Chimica", "L"),
        ("Ingegneria Chimica", "LM"),
        ("Ingegneria dei Materiali", "LM"),
        ("Ingegneria dei Materiali e Biomateriali", "L"),
        ("Ingegneria Gestionale", "L"),
        ("Ingegneria Gestionale", "LM"),
        ("Ingegneria Meccanica", "L"),
        ("Ingegneria Meccanica per l'Energia e l'Ambiente", "LM"),
        ("Ingegneria Meccanica per la Progettazione e la Produzione", "LM"),
        ("Ingegneria Navale", "L"),
        ("Ingegneria Navale", "LM"),
        ("Ingegneria Navale (cadetti Accademia Navale di Livorno)", "L"),
    ],
    "Medicina e Chirurgia": [
        ("Medicina e Chirurgia", "CU"),
        ("Medicina e Chirurgia ad Indirizzo Tecnologico (MediTec)", "CU"),
        ("Medicine and Surgery", "CU"),
        ("Odontoiatria e Protesi Dentaria", "CU"),
        ("Farmacia", "CU"),
        ("Chimica e Tecnologia Farmaceutiche", "CU"),
        ("Biotecnologie del Farmaco", "LM"),
        ("Biotecnologie Mediche", "LM"),
        ("Biotecnologie per la Salute", "L"),
        ("Controllo di Qualità", "L"),
        ("Scienza e Tecnologia dell'Industria Cosmetica", "LM"),
        ("Scienze e Tecnologie Erboristiche", "L"),
        ("Scienze Nutraceutiche", "L"),
        ("Scienze della Nutrizione Umana", "LM"),
        ("Tossicologia Chimica e Ambientale", "LM"),
        ("Ottica e Optometria", "L"),
        # Professioni sanitarie
        ("Dietistica", "L"),
        ("Fisioterapia", "L"),
        ("Igiene Dentale", "L"),
        ("Infermieristica", "L"),
        ("Infermieristica Pediatrica (ad esaurimento)", "L"),
        ("Logopedia", "L"),
        ("Ortottica ed Assistenza Oftalmologica", "L"),
        ("Ostetricia", "L"),
        ("Tecniche Audiometriche", "L"),
        ("Tecniche Audioprotesiche", "L"),
        ("Tecniche della Prevenzione nell'Ambiente e nei Luoghi di Lavoro", "L"),
        ("Tecniche di Fisiopatologia Cardiocircolatoria e Perfusione Cardiovascolare", "L"),
        ("Tecniche di Laboratorio Biomedico", "L"),
        ("Tecniche di Neurofisiopatologia", "L"),
        ("Tecniche di Radiologia Medica per Immagini e Radioterapia", "L"),
        ("Tecniche Ortopediche", "L"),
        ("Terapia Occupazionale", "L"),
        ("Scienze delle Professioni Sanitarie - Area Tecnico Assistenziale", "LM"),
        ("Scienze delle Professioni Sanitarie della Prevenzione", "LM"),
        ("Scienze delle Professioni Sanitarie Tecniche - Area Tecnico-Diagnostica", "LM"),
        ("Scienze Infermieristiche ed Ostetriche", "LM"),
        ("Scienze Riabilitative delle Professioni Sanitarie", "LM"),
    ],
    "Agraria e Medicina Veterinaria": [
        ("Medicina Veterinaria", "CU"),
        ("Veterinary Medicine", "CU"),
        ("Biotecnologie Agro-Ambientali ed Alimentari", "LM"),
        ("Gestione degli Animali e delle Produzioni", "L"),
        ("Precision Livestock Farming", "LM"),
        ("Scienze Agrarie, Forestali e Ambientali", "L"),
        ("Scienze e Tecnologie Agrarie", "LM"),
        ("Scienze e Tecnologie Alimentari", "LM"),
        ("Scienze e Tecnologie delle Produzioni Animali", "LM"),
        ("Scienze Enologiche", "LM"),
        ("Scienze Forestali e Ambientali", "LM"),
        ("Scienze Gastronomiche Mediterranee", "L"),
        ("Sustainable Food Systems", "LM"),
        ("Tecnologie Alimentari", "L"),
        ("Viticoltura ed Enologia", "L"),
    ],
    "Scienze Umane e Sociali": [
        # Giurisprudenza
        ("Giurisprudenza", "CU"),
        ("Scienze dei Servizi Giuridici", "L"),
        # Economia
        ("Economia Aziendale", "L"),
        ("Economia Aziendale", "LM"),
        ("Economia delle Imprese Finanziarie (CLEIF)", "L"),
        ("Economia e Commercio (CLEC)", "L"),
        ("Economia e Commercio (LMEC)", "LM"),
        ("Economics and Finance", "LM"),
        ("Finanza (LMF)", "LM"),
        ("Hospitality Management (professionalizzante)", "L"),
        ("Innovation and International Management", "LM"),
        ("Scienze del Turismo a Indirizzo Manageriale (STIM)", "L"),
        # Scienze politiche e sociali
        ("Comunicazione Pubblica, Sociale e Politica", "LM"),
        ("Culture Digitali e della Comunicazione", "L"),
        ("Digital Society, Social Innovation and Global Citizenship", "LM"),
        ("Gestione delle Politiche e dei Servizi Sociali", "LM"),
        ("Innovazione Sociale", "LM"),
        ("International Relations", "LM"),
        ("Relazioni Internazionali, Integrazione Europea e Sostenibilità", "LM"),
        ("Scienze Antropologiche e Geografiche (S.a.g.e.)", "LM"),
        ("Scienze Criminologiche, Investigative e di Contrasto ai Crimini Informatici", "LM"),
        ("Scienze del Servizio Sociale", "L"),
        ("Scienze dell'Amministrazione e dell'Organizzazione", "L"),
        ("Scienze della Pubblica Amministrazione e del Lavoro", "LM"),
        ("Scienze Politiche", "L"),
        ("Scienze Statistiche per le Decisioni", "LM"),
        ("Sociologia", "L"),
        ("Sociologia Digitale e Analisi del Web", "LM"),
        ("Statistica e Tecnologie per l'Analisi dei Dati", "L"),
        # Studi umanistici
        ("Archeologia del Mediterraneo", "LM"),
        ("Archeologia e Storia dell'Arte (ad esaurimento)", "LM"),
        ("Archeologia, Storia delle Arti e Scienze del Patrimonio Culturale", "L"),
        ("Coordinamento dei Servizi Educativi per la Prima Infanzia e per il Disagio Sociale", "LM"),
        ("Discipline della Musica e dello Spettacolo. Storia e Teoria", "LM"),
        ("Filologia Moderna", "LM"),
        ("Filologia, Letterature e Civiltà del Mondo Antico", "LM"),
        ("Filosofia", "L"),
        ("Filosofia", "LM"),
        ("Lettere Classiche", "L"),
        ("Lettere Moderne", "L"),
        ("Lingue e Letterature per il Plurilinguismo Europeo", "LM"),
        ("Lingue, Culture e Letterature Moderne Europee", "L"),
        ("Management del Patrimonio Culturale", "LM"),
        ("Patrimonio Culturale, Storia delle Arti e Museologia", "LM"),
        ("Psicologia Clinica e degli Interventi nei Contesti Sociali e dello Sviluppo", "LM"),
        ("Scienze e Tecniche Psicologiche", "L"),
        ("Scienze Storiche", "LM"),
        ("Storia", "L"),
    ],
}


def course_label(name, kind):
    return "%s · %s" % (name, TYPE_LABELS[kind])


def grouped_labels():
    """[(scuola, [etichette ordinate])] per il menu a tendina."""
    return [(school, sorted((course_label(n, k) for n, k in items), key=str.lower))
            for school, items in COURSES.items()]


ALL_LABELS = {course_label(n, k) for items in COURSES.values() for n, k in items}
